services:
  project:
    container_name: project
    image: project
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    environment:
      CONN_STRING: 'postgres://user:user@db:5432/user-db'
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user-db
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/pg_isready -d postgres -U user" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s 
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - net
      
volumes:
  db-data:

networks:
  net: