basePath: /
definitions:
  handlers.NewPassword:
    properties:
      value:
        type: string
    required:
    - value
    type: object
host: localhost:8080
info:
  contact: {}
  license:
    name: Apache 2.0
  title: Project Swagger
  version: "0.1"
paths:
  /admin/changeAdminPassword:
    post:
      consumes:
      - application/json
      parameters:
      - description: new password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.NewPassword'
      produces:
      - application/json
      responses: {}
      security:
      - BasicAuth: []
      summary: ChangeAdminPassword
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
